---

- name: Install Nginx
  apt: name=nginx state=installed
  tags: packages

# - name: Copy the SSL certificate to the remote server
#   copy: content="{{ ssl_crt }}" dest={{ ssl_dest_dir }}/{{ application_username }}.crt
#   notify: restart nginx

# - name: Copy the SSL private key to the remote server
#   copy: content="{{ ssl_key }}" dest={{ ssl_dest_dir }}/{{ application_username }}.key
#   notify: restart nginx

- name: Create the Nginx configuration file
  template: src=nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_username }}
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default
  notify: reload nginx

- name: Ensure that the application site is enabled
  command: ln -s /etc/nginx/sites-available/{{ application_username }}
           /etc/nginx/sites-enabled/{{ application_username }}
           creates=/etc/nginx/sites-enabled/{{ application_username }}
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
