# vim: sw=2:noai
---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} executable=pip3 requirements={{ requirements_file }}

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ managepy_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ managepy_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
