# vim: sw=2:noai
---
- name: Install Base Packages
  hosts: vagrant
  sudo: yes
  sudo_user: root
  remote_user: vagrant

  roles:

    - base

    - role: app
      project_name: "spacedonkey.org"
      nginx_server_name: "192.168.33.15.xip.io"
      application_username: "spacedonkey"
      git_repo: "https://github.com/mooja/spacedonkey.org/"
      git_branch: "master"
