# vim: sw=2:noai
---
- name: Install Base Packages
  hosts: webapp
  remote_user: root
  become: yes

  roles:

    - base

    - role: app
      project_name: "spacedonkey.org"
   #  nginx_server_name: "spacedonkey.org"
      application_username: "spacedonkey"
      git_repo: "https://github.com/mooja/spacedonkey.org/"
      git_branch: "master"
